apiVersion: apps/v1
kind: Deployment
metadata:
    name: rediss
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rediss
    minReadySeconds: 15
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: rediss
        spec:
            containers:
                - name: rediss
                  image: redislabs/rejson:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 6379
