apiVersion: v1
kind: Service
metadata:
    name: rediss-lb
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: 6379
    selector:
        app: rediss
