apiVersion: v1
kind: Service
metadata:
    name: react-midterm-lb
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: react-midterm